### ISSUE TITLE
Move add_padding to adjust

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1202]
add_padding needs to be moved from the converter to the adjuster. 

### Previous attempt: 
- https://github.com/esbmc/esbmc/tree/adjust_type
 
### Evaluation: 
- https://github.com/esbmc/esbmc/pull/1180#issuecomment-1640012394

**Comment by fbrausse** [comment]
In https://github.com/fbrausse/esbmc/tree/fb/adjust_type I've given it another try but now I don't quite know what's the best way to continue. It's based on the @kunjsong01's latest approach in <https://github.com/esbmc/esbmc/pull/1180#issuecomment-1640012394> and has two patches:
- https://github.com/esbmc/esbmc/commit/d932f610b91f41ca4bdf20504378592a2429274d
- https://github.com/esbmc/esbmc/commit/0c957fbc6f82d63c3d1db5d415e4c3dd21768fa9

I've added comments about what conditions hold true and how I would like to proceed here, but since now quite some refactoring could be needed I thought it best to get your opinions in this approach first.

In `get_struct_union_class()` one change is to properly construct "incomplete_union" and "incomplete_struct" if Clang doesn't have a definition. That' not too controversial, I guess.

Then, basically, we're putting the symbol first with symbolic type into the context, recursively resolve the member fields (which might make copies of the symbolic type that's now in the context), and then I would like to kind-of selectively do thrash_type_symbols(). Selectively, because by the recursive structure of clang_c_convert, we'd already know that all new types for members will have been "thrashed". Only those of the current symbol (and its call stack) are left. So we'd just need to replace the symbolic types referring to the current symbol.

Since that's not accessible, this version currently fails in add_padding(), specifically in type_byte_size() on something like this (from #637):
```
struct
  * tag: struct T
  * components: 
    0: component
        * type: symbol
            * identifier: tag-struct S
            * #location: 
              * file: gh-637-1.c
              * line: 3
              * column: 1
        * name: s
        * pretty_name: s
        * #location: 
          * file: gh-637-1.c
          * line: 8
          * column: 2
  * #location: 
    * file: gh-637-1.c
    * line: 7
    * column: 1
```
@kunjsong01 @mikhailramalho Would it be an option to move `thrash_type_symbols()` from goto_convert_functionst to contextt? That way we would avoid duplicating it and could call in adjust (or add_padding).

Another option could be to just extend the type_byte_size() family of functions with a namespace parameter.

Do you maybe have other suggestions?

**Comment by mikhailramalho** [comment]
> In https://github.com/fbrausse/esbmc/tree/fb/adjust_type I've given it another try but now I don't quite know what's the best way to continue. It's based on the @kunjsong01's latest approach in [#1180 (comment)](https://github.com/esbmc/esbmc/pull/1180#issuecomment-1640012394) and has two patches:
> 
> * [d932f61](https://github.com/esbmc/esbmc/commit/d932f610b91f41ca4bdf20504378592a2429274d)
> * [0c957fb](https://github.com/esbmc/esbmc/commit/0c957fbc6f82d63c3d1db5d415e4c3dd21768fa9)
> 
> I've added comments about what conditions hold true and how I would like to proceed here, but since now quite some refactoring could be needed I thought it best to get your opinions in this approach first.
> 
> In `get_struct_union_class()` one change is to properly construct "incomplete_union" and "incomplete_struct" if Clang doesn't have a definition. That' not too controversial, I guess.

In which case we don't have a complete definition and need to call `get_struct_union_class()`? If we don't have a complete definition, can't we use a symbol_typet and resolve it later as needed? Maybe it's something related to vtables?

> 
> Then, basically, we're putting the symbol first with symbolic type into the context, recursively resolve the member fields (which might make copies of the symbolic type that's now in the context), and then I would like to kind-of selectively do thrash_type_symbols(). Selectively, because by the recursive structure of clang_c_convert, we'd already know that all new types for members will have been "thrashed". Only those of the current symbol (and its call stack) are left. So we'd just need to replace the symbolic types referring to the current symbol.
> 

If we got ahead with symbol_typets everywhere, we might get of rid thrash_type_symbols() all together in the future, right?

> @kunjsong01 @mikhailramalho Would it be an option to move `thrash_type_symbols()` from goto_convert_functionst to contextt? That way we would avoid duplicating it and could call in adjust (or add_padding).
> 
> Another option could be to just extend the type_byte_size() family of functions with a namespace parameter.

I agree with adding the namespace to type_byte_size, since we have symbols there now.

> 
> Do you maybe have other suggestions?

**Comment by fbrausse** [comment]
> > In `get_struct_union_class()` one change is to properly construct "incomplete_union" and "incomplete_struct" if Clang doesn't have a definition. That' not too controversial, I guess.
> 
> In which case we don't have a complete definition and need to call `get_struct_union_class()`? If we don't have a complete definition, can't we use a symbol_typet and resolve it later as needed? Maybe it's something related to vtables?

This is just for forward declarations. When Clang doesn't have a definition, there is none in this translation unit and this type will remain incomplete forever (well, until migrate_type() decides it's fine to replace with get_uint8_type(), which is a bit questionable but might be fine; I didn't look into it, yet). Something like `opaque` in
```c
struct opaque;
typedef struct opaque *data_t;
```

> If we got ahead with symbol_typets everywhere, we might get of rid thrash_type_symbols() all together in the future, right?

Could be. :) Do we want to? I remember you suggested this when removing the union-flattening. Do the symbolic types serve any purpose in the rest of ESBMC at the moment?

> I agree with adding the namespace to type_byte_size, since we have symbols there now.

I'm trying this approach, yes. Atm. I'm fighting against incompatible types in symex_asssign: one side has padding applied and the other one doesn't. E.g. for `regression/esbmc-unix2/01_pthread60`:
```
[...]
src/irep2/irep2_expr.cpp:382: void assert_type_compat_for_with(const type2tc&, const type2tc&): Assertion `a == b' failed.

(gdb) p a->dump()
struct
* members : 
  0: pointer
    * subtype : symbol
        * symbol_name : tag-struct _barrier
  1: pointer
    * subtype : symbol
        * symbol_name : tag-struct _barrier
  2: signedbv
    * width : 32

* member_names : 
  0: b1
  1: b2
  2: tid

* member_pretty_names : 
  0: b1
  1: b2
  2: tid

* typename : struct __anon_typedef_Arg_at_main_c__61_9
* packed : false

(gdb) p b->dump()
struct
* members : 
  0: pointer
    * subtype : symbol
        * symbol_name : tag-struct _barrier
  1: pointer
    * subtype : symbol
        * symbol_name : tag-struct _barrier
  2: signedbv
    * width : 32
  3: unsignedbv
    * width : 32

* member_names : 
  0: b1
  1: b2
  2: tid
  3: anon_pad$3

* member_pretty_names : 
  0: b1
  1: b2
  2: tid
  3: anon_pad$3

* typename : struct __anon_typedef_Arg_at_main_c__61_9
* packed : false
```
This is in the context of (`goto_symext::symex_assign_array`).

**Comment by mikhailramalho** [comment]
> This is just for forward declarations. When Clang doesn't have a definition, there is none in this translation unit and this type will remain incomplete forever (well, until migrate_type() decides it's fine to replace with get_uint8_type(), which is a bit questionable but might be fine; I didn't look into it, yet). Something like `opaque` in
> 
> ```c
> struct opaque;
> typedef struct opaque *data_t;
> ```

Right, but can't we just make it a symbol_typet? Specially if we are only dealing with pointers in this case, they should always be a symbol_typet + the zero init is trivial.

> 
> > If we got ahead with symbol_typets everywhere, we might get of rid thrash_type_symbols() all together in the future, right?
> 
> Could be. :) Do we want to? I remember you suggested this when removing the union-flattening. Do the symbolic types serve any purpose in the rest of ESBMC at the moment?

I'm not sure tbh, Jeremy removed it a long time ago because reasons? I don't remember why, but it definitely simplifies a lot of code (no need to .lookup() when we see a symbol_typet).

> 
> > I agree with adding the namespace to type_byte_size, since we have symbols there now.
> 
> I'm trying this approach, yes. Atm. I'm fighting against incompatible types in symex_asssign: one side has padding applied and the other one doesn't. E.g. for `regression/esbmc-unix2/01_pthread60`:

Maybe the adjust code is missing a call somewhere?
