### ISSUE TITLE
What's k in the result?

### ISSUE THREAD

**Issue by pmatos** [esbmc/esbmc#130]
Same example as #129 

`fact.c`:
```
#include <stdio.h>

unsigned int fact (unsigned int n) {
  unsigned int f = 1;
  while (n != 0)
      f *= n--;

  return f;
}
```

`fact_props.c`:
```
#include "fact.c"


void check_fact (void)
{
  unsigned int n = nondet_uint ();
  unsigned int f = fact (n);

  assert (f > n);
}
```

Run:
```
$ ~/installs/esbmc+python-v6.1.0-linux-static-64/bin/esbmc fact_props.c --function check_fact --k-induction-parallel --boolector --64
...
...
...
VERIFICATION FAILED
BASE CASE PROCESS FINISHED.
Not unwinding loop 2 iteration 3 file fact.c line 7 function fact

Bug found by the base case (k = 1)
VERIFICATION FAILED
```

Found bug in base case, `k=1`? There's no variable `k` in my program? I assume this is related to `k` induction, however, there's no explanation to what this is and it doesn't look like it's a counterexample.

**Comment by mikhailramalho** [comment]
The `k` is the number of loop unwindings needed to find the violation. I agree it is not the most useful message, we'll work on it.

Regarding the counterexample, may I ask to use the sequential k-induction for now? 

The parallel version hasn't is pretty outdated and it's being fixed in a separate branch (kind). We will disable it for the next release but re-enable it in the near future.

**Comment by pmatos** [comment]
@mikhailramalho Thanks - closing.
