### ISSUE TITLE
dereference failure: accessed expired variable pointer `c:pointer.c@129@F@main@incr'

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#152]
This C program seems to be correct but ESBMC v6.2 fails to check both assertions.

$esbmc pointer.c

```
#include <assert.h>
#include <pthread.h>
void *t1(void *arg) {
  int *ptr = arg;
  assert(*ptr==1);
  return 0;
}
int main() {
  int *p, incr=0;
  pthread_t id;
  incr++;
  p = &incr;
  pthread_create(&id, NULL, t1, &incr);
  assert(*p==1);
  return 0;
}
```

```
Counterexample:

State 3 file assert.h line 93 function t1 thread 1
----------------------------------------------------
Violated property:
  file assert.h line 93 function t1
  dereference failure: accessed expired variable pointer `c:pointer.c@130@F@main@incr'
  !((_Bool)((signed long int)(!(*ptr == 1))))
```

@jmorse: do you have any thoughts?

**Comment by mikhailramalho** [comment]
The problem here is that `main` is finished but before `pthread_end_main_hook` is called, `t1` is being scheduled and it correctly asserts that we are referencing a dead variable.

I think the fix should be force calling `pthread_end_main_hook` whenever we reach the end of `main` and kill every interleaving in that branch. Don't ask me how to implement this though.

**Comment by lucasccordeiro** [comment]
This PR https://github.com/esbmc/esbmc/pull/226 should fix this issue.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/596.
