### ISSUE TITLE
ESBMC giving nondeterministic results with option --parallel-solving

### ISSUE THREAD

**Issue by salvadorer** [esbmc/esbmc#1528]
Dear all, 
recently I found out that ESBMC may give different results when analyzing the same file with the same arguments.
Consider the following code:
```
#include <assert.h>
extern int __VERIFIER_nondet_int(void);

int main() {
  int N = 1;
  int src[N];
  int dst[N];
  src[0] = __VERIFIER_nondet_int();
  dst[0] = src[0];
  assert(dst[0] == src[0]);
  return 0;
}
```
When executing `~/esbmc-linux/linux-release/bin/esbmc --parallel-solving --array-flattener test.c` one might obtain an output ending with
```
[Counterexample]


State 1 file test.c line 8 column 12 function main thread 0
----------------------------------------------------
  src[0] = -33 (11111111 11111111 11111111 11011111)

State 2 file test.c line 9 column 3 function main thread 0
----------------------------------------------------
  dst[0] = -536870913 (11011111 11111111 11111111 11111111)

State 3 file test.c line 10 column 3 function main thread 0
----------------------------------------------------
Violated property:
  file test.c line 10 column 3 function main
  assertion dst[0] == src[0]
  dst[0] == src[0]


VERIFICATION FAILED 
```
This however only occurs with a 1% chance when executing ESBMC. Mostly one would receive an output ending with `VERIFICATION SUCCESSFUL` (as expected). You should be able to reproduce this by executing the shell script [script.zip](https://github.com/esbmc/esbmc/files/13498369/script.zip)  .
I know that in this case this is a precision issue. However I also found a case where it is a soundness issue, but the input file is huge and therefore it would be harder to reproduce this.
I am working with ESBMC version 7.4.0 64-bit x86_64 linux.

**Comment by lucasccordeiro** [comment]
Dear @salvadorer,

Thank you very much for this report.

In the most recent versions of ESBMC (you can get them from https://github.com/esbmc/esbmc/releases), we removed the support for `--parallel-solving` due to data race issues in ESBMC. It will take us some time to fix these issues in ESBMC.

We recommend using our latest nightly build release to ensure you no longer use this option. Instead, you could use the option `--k-induction-parallel`, which we believe is very stable.

Please let us know if you have any questions.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/commit/ebcce19a469d33b69a7fe9a1ef9861b901b51ceb and https://github.com/esbmc/esbmc/commit/7b41f37e9712db3a071ddb2fc9875fef38816aec.
