### ISSUE TITLE
ESBMC missing a warning when dropping an irrelevant assumption

### ISSUE THREAD

**Issue by salvadorer** [esbmc/esbmc#1537]
Hi,
I just executed `esbmc-linux/linux-release/bin/esbmc --multi-property test.c` with the following code:

```
#include <assert.h>
#include <stddef.h>
extern void __VERIFIER_assume(int);

int main(){
  __VERIFIER_assume(NULL != "a");
  char *str0 = (char *) 0xFFFFFFFFFFFFFFFF;
  char *str1 = "";
  assert(str0 <= str1);
}
```
ESBMC corretly warns me about the assertion, however if I drop the (completely irrelevant) assumption, it doesn't do so, even tough the assertion would clearly still fail.
I am working with ESBMC version 7.4.0 64-bit x86_64 linux.

**Comment by lucasccordeiro** [comment]
Dear @salvadorer,

Thanks for reporting this issue.

This bug has been fixed in the master branch of ESBMC.

If you can't compile ESBMC from the master branch, you should be able to download the fixed version of the ESBMC binary on Monday (25/12) from https://github.com/esbmc/esbmc/releases.

If you encounter further issues, please let us know.
