### ISSUE TITLE
ESBMC unable to reason about symbolic indexes properly

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1622]
In the following program:

```c
#include <stdio.h>
#include <assert.h>
#define UINT8  unsigned char
#define UINT16 unsigned short int
#define UINT32 unsigned long
#define UINT64 unsigned long long

typedef struct {
	UINT32                       Offset;
	UINT32                       Width;
	UINT64                       Value;
	char* Name;
	UINT64                       Reserved;
} REGMAP_ENTRY; 

typedef struct {
    REGMAP_ENTRY* RegMap;
} REGMAP_TABLE; 

REGMAP_ENTRY m_PORT_RegMap[] = {
  {0x0,   32, 0x00000800, "REG0", 0xFFFF0000},
  {0x0,   32, 0x00000800, "REG1", 0xFFFF0000},
  {0x0,   32, 0x00000800, "REG2", 0xFFFF0000},
  {0x0,   32, 0x00000800, "REG3", 0xFFFF0000}
};

REGMAP_TABLE m_PORT_RegMapTable = {
  m_PORT_RegMap
};

typedef struct {
    void *       RegCntxtPortList1[4];
} IP_INST;

int main()
{
    IP_INST* pInst;
    pInst = malloc(sizeof(IP_INST));
    
    // SOMETHING WEIRD HERE
    int PortIdx = 0;    
    pInst->RegCntxtPortList1[PortIdx] = &m_PORT_RegMapTable;
    REGMAP_TABLE* RegMapTable = pInst->RegCntxtPortList1[PortIdx];
    REGMAP_ENTRY* pRegmap = &(RegMapTable->RegMap[3]);
    assert(pRegmap != 0);
    free(pInst);
    return 0;
}

int main_fixed()
{
    IP_INST* pInst;
    pInst = malloc(sizeof(IP_INST));
    
    // No PortIdx
    pInst->RegCntxtPortList1[0] = &m_PORT_RegMapTable;
    REGMAP_TABLE* RegMapTable = pInst->RegCntxtPortList1[0];
    REGMAP_ENTRY* pRegmap = &(RegMapTable->RegMap[3]);
    assert(pRegmap != 0);
    free(pInst);
    return 0;
}
```

In the function `main` the variable `PortIdx` is used to get a position of the array. Running `esbmc --force-malloc-success` will result in the assertion failing (the assertion passes when running with GCC). However, replacing the variable with its value (at `main_fixed`) solves the issue. This may be related to: https://github.com/esbmc/esbmc/issues/1458#issuecomment-1806090365

**Comment by fbrausse** [comment]
This statement appearently is modelled as byte extracts:
```c
    REGMAP_TABLE* RegMapTable = pInst->RegCntxtPortList1[PortIdx];
```
And extracting from the wrong object at that:
```
  RegMapTable = ( struct __anon_typedef_REGMAP_TABLE_at_gh-1622_c__16_9 *)((void *)(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(byte_extract_little_endian(&{ .RegMap=nil }, 7), byte_extract_little_endian(&{ .RegMap=nil }, 6)), byte_extract_little_endian(&{ .RegMap=nil }, 5)), byte_extract_little_endian(&{ .RegMap=nil }, 4)), byte_extract_little_endian(&{ .RegMap=nil }, 3)), byte_extract_little_endian(&{ .RegMap=nil }, 2)), byte_extract_little_endian(&{ .RegMap=nil }, 1)), byte_extract_little_endian(&{ .RegMap=nil }, 0))))
```
Probably related: the value-set isn't correctly updated for this assignment:
```
        pInst->RegCntxtPortList1[(signed long int)PortIdx]=(void *)(&m_PORT_RegMapTable);


symex_dynamic::dynamic_2_value.RegCntxtPortList1[] = { * } 
```

**Comment by rafaelsamenezes** [comment]
> Probably related: the value-set isn't correctly updated for this assignment:

Yeah, VSA seems to be the main culprit. 😔

**Comment by lucasccordeiro** [comment]
Is our VSA enabled by default now?

**Comment by rafaelsamenezes** [comment]
> Is our VSA enabled by default now?

This is the symex one, which is always enabled. The one at GOTO level is only enabled for gcse.

**Comment by fbrausse** [comment]
The alignment in construct_from_array() is determined to be 1 byte when dereferencing `pInst->RegCntxtPortList1[PortIdx]`. Therefore, that function assumes that `overflows_boundaries` is true, because `is_correctly_aligned` is computed to be false - both are wrong, and we should actually be able to statically determine whether the dynamic object is correctly aligned for that dereference. When setting `overflows_boundaries` to false for those dereferences, the result is VERIFICATION SUCCESSFUL.

Seems to me that there actually are 2 different issues here:
1. The alignment computation in the value_set gives the dynamically allocated symbol an alignment of 1 byte where it should be larger or equal to that of max_align_t.
2. The byte-extract path in construct_from_array() is not equivalent to just indexing into the array for correctly aligned values.

We did already find problems related to the dynamic index and alignment in #1220.
