### ISSUE TITLE
Segmentation fault while encoding in Boolector

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#169]
Executing esbmc with boolector and the flags `--no-bounds-check --no-pointer-check --no-div-by-zero-check --incremental-bmc --max-k-step 10` gives a Segmentation fault in the following program:

```
a;
void h();
#define c(d, g) strcmp(d, 0)
main(argc, argv) char **argv;
{
  char *b[argc];
  char e;
  for (; e;)
    *b = a;
  h(b);
}
void h(f) { c(f, ); }
```

Using Z3 this fault does not happen.

**Comment by mikhailramalho** [comment]
It seems to be a bug in the tuple node flattener. 

While I'm trying to fix it, you can use --tuple-sym-flattener in the cmdline and it should work.

**Comment by lucasccordeiro** [comment]
The option `--no-pointer-check` causes the segmentation fault in ESBMC.

**Comment by lucasccordeiro** [comment]
The current ESBMC master fails with this error message:

````
terminate called after throwing an instance of 'array_type2t::dyn_sized_array_excp'
````

@fbrausse: do you have any suggestions here?

**Comment by fbrausse** [comment]
This happens in `smt_convt::convert_byte_extract()` on the `b` array. We're trying to byte-extract from a dynamically-sized array, which is appearently not supported. The byte_extract expression is created in dereferencet::construct_from_const_offset() for an index-expr into `b`, which is appearently supposed to be handled in https://github.com/esbmc/esbmc/blob/94b1ae7d9b076d7928cc6a936e7a8decc2288876/src/pointer-analysis/dereference.cpp#L1972

@shmarovfedor Do you know why we're byte-extracting from an array in this case instead of byte-extracting from the index-expression into that array?

**Comment by shmarovfedor** [comment]
@fbrausse As far as I remember, this is done so that we do not need to worry about how many indices are involved into a byte-extract. This is because sometimes we might have a situation where we need to extract only a single byte (e.g., extracting a bit-field) from a given array index which means that we will have to deal with a combination of "whole" and "partial" array elements. So we use the index information to update the offset and then just extract bytes from the array symbol instead. I hope this explanation makes sense.

**Comment by fbrausse** [comment]
@shmarovfedor Please correct me if I'm wrong, but isn't it the case that an `array[idx]` expression always refers to a byte-aligned offset and an integral number of bytes? Do you remember whether there were any test cases that benefit from this?

**Comment by shmarovfedor** [comment]
@fbrausse you are correct. `array[idx]` indeed refers to a byte-aligned offset into the `array` object. However, you can have a situation where you need to extract bytes from an array with an offset that is not aligned to a byte. For example, extracting a bitfield (a potential non-byte-aligned offset) from a struct object on the heap (which is represented by a byte array). As far as I remember, this was the only scenario where this was necessary.

**Comment by fbrausse** [comment]
OK, many thanks, I'll take a look what we can do.

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse and @shmarovfedor. This issue has been hanging around for quite some time in ESBMC. I believe this issue was reported by our collaborators at Intel.

**Comment by lucasccordeiro** [comment]
@fbrausse: Can I ask whether you had a chance to look at this issue?

**Comment by fbrausse** [comment]
@lucasccordeiro There is a PR fixing it linked to this issue: #1188.

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.
