### ISSUE TITLE
[C++ operational models] Add support for the <cmath> lib

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1704]
This feedback was provided by one of our industrial partners:

_``The code uses float_t and round which are defined in <cmath>. The version of <cmath> that is installed on our Linux machines doesn’t have it. However, experimental industrial tool for C/C++ verification does support it. I worked around it by defining both in esbmc.hpp, but I believe it must be supported by ESBMC straightforward through <cmath> support.``_

**Comment by lucasccordeiro** [comment]
@fbrausse: can I ask you whether you would have any suggestions here to solve this issue?

**Comment by fbrausse** [comment]
The two symbols should be in <math.h>, which \<cmath\> includes.

IIUC, the request is for ESBMC to provide type float_t and function round() in <math.h> even if the system's libc for some reason doesn't. round() we already model, but we don't have an own <math.h> and instead refer to the system's. As far as I remember, that choice was made for compatibility with Free-/CheriBSD and I'll look into providing one.

However, it would be good to know what system the industrial partner is using, and why their <math.h> or \<cmath\> doesn't provide these types/declarations, in order to reproduce the problem.

**Comment by lucasccordeiro** [comment]
I have just tried the following example with the data structure and function from cmath mentioned here:

````CPP
#include <iostream>
#include <cmath>
#include <cassert>

int main() {
    // Define a floating point variable
    float_t x = 3.5;

    // Use the round function to round x to the nearest integer
    float_t rounded_x = round(x);

    // Print the rounded value
    std::cout << "Rounded value of " << x << " is " << rounded_x << std::endl;

    // Assertion to check if rounding is correct
    assert(rounded_x == 4);

    return 0;
}
````

ESBMC can handle this code:

````
ESBMC version 7.5.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing mat.cpp
Converting
Generating GOTO Program
GOTO program creation time: 1.138s
GOTO program processing time: 0.057s
Starting Bounded Model Checking
Symex completed in: 0.027s (186 assignments)
Slicing time: 0.002s (removed 182 assignments)
Generated 1 VCC(s), 1 remaining after simplification (4 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.008s
Solving with solver Boolector 3.2.2
Runtime decision procedure: 0.002s
BMC program time: 0.038s

VERIFICATION SUCCESSFUL
````

**Comment by fbrausse** [comment]
Please reopen if there is more information about the actual issue.
