### ISSUE TITLE
[C++ Frontend] Recursive, extending structs via pointers: `Assertion 'type.id() == typet::t_struct || type.id() == typet::t_union || type.id() == typet::t_class' failed.`

### ISSUE THREAD

**Issue by intrigus-lgtm** [esbmc/esbmc#1776]
`a` refers to `b` via a pointer.
So when we try to parse the `a`, we will notice the field `c` with the type `b`.
Then we will try to get the type for `b`.
However, now `b` will try to get the type for its base class: `a`.
And now we will call `to_struct_type(class_a)` which will fail, because `a` is not yet a complete type.

I tried a bit to fix this, but wasn't very successful so far.

I think @fbrausse was working on recursive structs last time, so maybe he has an idea.

```cpp
class a;
class b;
class a {
  b *c;
};
class b : a {};
```

```shell
esbmc: esbmc/src/util/std_types.h:251: struct_typet& to_struct_type(typet&): Assertion `type.id() == typet::t_struct || type.id() == typet::t_union || type.id() == typet::t_class' failed.
```

**Comment by fbrausse** [comment]
This looks similar to #637, which ultimately was fixed by using the `type.incomplete()` flag in https://github.com/esbmc/esbmc/blob/7736aca9b39e7449d4409bd12863220eab730d79/src/clang-c-frontend/clang_c_convert.cpp#L357-L362 as a way to stop the recursion. Maybe the C++ frontend could also check this flag? Note that the flag is currently cleared directly after the return, so before the C++ convert functions are invoked. That clearing would need to be moved down to the end, so the flag retains its meaning for the C++ frontend.

----------------------

In the past different approaches to this tricky get_struct_union_class() were discussed, but they've been deemed too invasive. One maybe not so invasive way could be:
- get_struct_union_class() always stops at the above point, only leaving `incomplete_*` in the context until all top-level declarations are performed.
- Additionally, this method would put the new incomplete type (together with the Clang AST node) into a stack called `yet_to_be_defined`.
- At the end of convert_top_level_decl() there would be a loop iterating over `yet_to_be_defined` and pulling in the complete definitions via the second half of get_struct_union_class() that step 1 now skips. This loop needs to be a fixpoint search, because translating the complete type could put more incomplete ones onto the stack.
