### ISSUE TITLE
[overflow] ESBMC seems to miss an arithmetic overflow for multiplication operation 

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1779]
If we run ESBMC as 

$ esbmc norbert6.c --overflow-check --ssa-trace

````C
#include <stdio.h>
#include <math.h>

int main(int argc, char * argv[]){
    char data,result;
    /* OVERFLOW here*/
    data=13;
    result = data * data;
    printf("INCORRECT RESULT: %d\n", result);

}
````

We get:

````
ASSERT
execution_statet::\guard_exec?0!0 => !overflow("shl", 1, 5)
arithmetic overflow on shl

Thread 0
ASSUME
argc'&0#0 >= 1

Thread 0
ASSUME
argc'&0#0 <= 268435454

Thread 0 file norbert6.c line 8 column 5 function main
ASSERT
execution_statet::\guard_exec?0!0 => !overflow("*", (signed int)13, (signed int)13)
arithmetic overflow on mul

Thread 0 file norbert6.c line 9 column 5 function main
OUTPUT

Thread 0 file norbert6.c line 11 column 1 function main
ASSUME
0

Encoding to solver time: 0.002s
Solving with solver Boolector 3.2.2
Runtime decision procedure: 0.002s
BMC program time: 0.026s

VERIFICATION SUCCESSFUL
````

If we run ESBMC as

--overflow-check --smt-formula-only

We get:

````
$ esbmc norbert6.c --overflow-check --smt-formula-only
ESBMC version 7.5.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing norbert6.c
Converting
Generating GOTO Program
GOTO program creation time: 1.076s
GOTO program processing time: 0.133s
Starting Bounded Model Checking
Symex completed in: 0.024s (126 assignments)
Slicing time: 0.000s (removed 120 assignments)
Generated 19 VCC(s), 2 remaining after simplification (6 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.002s
(set-logic QF_BV)
(assert false)
(check-sat)
(exit)
````

**Comment by fbrausse** [comment]
This is not an overflow. The multiplication is performed on the integer-promoted types. We have had a similar case earlier, with a more detailed explanation, see #778.

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.

**Comment by maferrag** [comment]
@lucasccordeiro  : 

In practical terms, on most systems with standard 8-bit char, the value would wrap around using two's complement arithmetic (if char is signed). For example:

The binary representation of 169 is 10101001.

If char is signed, this value might typically be interpreted as negative (specifically -87 in two's complement).
To ensure the code is portable and behaves consistently across different platforms, it's usually better to use a larger integer type (like int) when you expect the results to exceed the range of char. Here's the adjusted part of your code with int for the result:

`int result;  // Use int here to store larger results safely.`

Using int for the result will handle the squared value without the risk of overflow or implementation-defined behavior, ensuring consistent behavior regardless of the compiler or platform.

This why we need to combine LLM and ESBMC to have better results.

**Comment by lucasccordeiro** [comment]
@maferrag: Here is what the C17 standard says:

source: http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf

````C
char c1, c2; /* ... */ c1 = c1 + c2;
````

_"The “integer promotions” require that the abstract machine promote the value of each variable to int size and then add the two ints and truncate the sum. Provided the addition of two chars can be done without overflow, or with overflow wrapping silently to produce the correct result, the actual execution need only produce the same result, possibly omitting the promotions."_

_"The integer promotions preserve value including sign. As discussed earlier, whether a “plain” char can hold negative values is implementation-defined."_

_"The integer promotions are applied only: as part of the usual arithmetic conversions, to certain argument expressions, to the operands of the unary+,- , and~ operators, and to both operands of the shift operators, as specified by their respective subclauses."_

**Comment by lucasccordeiro** [comment]
As pointed by @fbrausse in https://github.com/esbmc/esbmc/issues/778:

_"The cast back to char according to C is "implementation defined" (not undefined), see [C11 6.3.1.3/3](http://port70.net/~nsz/c/c11/n1570.html#6.3.1.3p3)."_

**Comment by maferrag** [comment]
@lucasccordeiro 

I used int8_t ... No overflow was detected. 

`#include <stdio.h>
#include <math.h>
#include <stdint.h>
int main(int argc, char** argv){
	char data, result;
	int8_t result_2;
	data = 13;
	result = data * data;
	printf("RESULT: %c\n", result);
	printf("RESULT: %d\n", result);
	result_2 = data* data;
	printf("Result2: %c\n", result_2);
	printf("result2: %d\n", result_2);
}`

Using int8_t from the <stdint.h> header in C provides a very specific guarantee: it is always an 8-bit signed integer. This type is part of the fixed width integer types introduced in C99 to provide exact-width integer types.

If we compute something like 13 * 13, which equals 169, and try to store this in an int8_t, it exceeds the maximum value that int8_t can hold (127). As a result, there will be an overflow.

Using int8_t does not prevent overflow in the scenario of squaring 13; it simply provides clarity that you are explicitly using an 8-bit signed integer. If we need to handle larger numbers safely, we should consider a larger type such as int16_t, int32_t, or simply int, depending on the expected range of our calculations.

**Comment by lucasccordeiro** [comment]
@maferrag: could you please point to a section in the C17 standard to support this claim?

``If we compute something like 13 * 13, which equals 169, and try to store this in an int8_t, it exceeds the maximum value that int8_t can hold (127). As a result, there will be an overflow.``

**Comment by fbrausse** [comment]
Hi @maferrag! I think it's a misunderstanding of the terminology: implicit conversion != overflow.

> If we compute something like 13 * 13, which equals 169, and try to store this in an int8_t, it exceeds the maximum value that int8_t can hold (127). As a result, there will be an overflow.

That's not what "overflow" means in the context of C: What happens here is that 13 * 13 is computed as `(int)13 * (int)13` due to the "usual arithmetic conversions" and the result again has type `int`. From [C11 6.5.5p3](https://port70.net/~nsz/c/c11/n1570.html#6.5.5p3) about multiplicative operators:
> The usual arithmetic conversions are performed on the operands.

Let's look at those usual arithmetic conversions in [C11 6.3.1.8p1](https://port70.net/~nsz/c/c11/n1570.html#6.3.1.8p1):
> - [... irrelevant cases involving floats ...]
> - Otherwise, the integer promotions are performed on both operands. Then the following rules are applied to the promoted operands: [...]

[C11 6.3.1.1p2](https://port70.net/~nsz/c/c11/n1570.html#6.3.1.1p2) tells us what integer promotions are:
> The following may be used in an expression wherever an int or unsigned int may be used:
> - An object or expression with an integer type (other than int or unsigned int) whose integer conversion rank is less than or equal to the rank of int and unsigned int.
> - [... irrelevant case for bitfields ...]
>
> If an int can represent all values of the original type (as restricted by the width, for a bit-field), the value is converted to an int; otherwise, it is converted to an unsigned int. These are called the integer promotions.[58)](https://port70.net/~nsz/c/c11/n1570.html#note58) All other types are unchanged by the integer promotions.

In essence: operands smaller than int get converted to int. The result is again of int type.

This int-typed result is converted to the type char in order to perform the assignment ([C11 6.5.16.1p2](https://port70.net/~nsz/c/c11/n1570.html#6.5.16.1p2)):
> In simple assignment (=), the value of the right operand is converted to the type of the assignment expression and replaces the value stored in the object designated by the left operand.

As quoted by Lucas above: this implicit conversion is not undefined, but implementation defined, meaning: there must be a result. This is desribed in [C11 6.3.1.3p3](https://port70.net/~nsz/c/c11/n1570.html#6.3.1.3p3):
> Otherwise, the new type is signed and the value cannot be represented in it; either the result is implementation-defined or an implementation-defined signal is raised.

So the implicit conversion back to `char` is implementation-defined, everything before and including the multiplication itself is clearly defined. With ESBMC, we generally try to follow the consensus of documented implementations, where possible, and the standards documents.

------------------------

The notion "overflow" refers to the following condition: the mathematical result of an arithmetic operation does not fit into the range provided by the type of the operation's result. Unfortunately, C does not provide a clear definition of "overflow", but the usage throughout the document always refers to overflows being generated by arithmetic operations. An implicit cast is not an arithmetic operation.

For instance, `INT_MAX + 1` is an overflow, but `(int8_t)INT_MAX` is not.
