### ISSUE TITLE
Release ESBMC v7.6

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1818]
Dear all,

I would like to release a new ESBMC version 7.6.

Do you have any PRs to consider for this release?

**Comment by fbrausse** [comment]
I'm good with the current state. No urgent PRs from my side.

**Comment by ChenfengWei0** [comment]
I'm also good with the current state. 
- The Solidity "mapping and built-in member" PR is nearly done. However, since the `realloc` issue is unfixed, I think we should not merge it into 7.6.
- The condition coverage PR still needs a lot of improvement and bug fixes. So it should not be merged into 7.6 either.

**Comment by brcfarias** [comment]
I don't have any pull requests to consider. I'm ok with the release for ESBMC.

**Comment by fbrausse** [comment]
I believe there is nothing left to do here. :)

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.
