### ISSUE TITLE
[QUESTION] Get SMT formula

### ISSUE THREAD

**Issue by Sakura-0407** [esbmc/esbmc#1829]
Hello, this is my cpp code, which is very simple. My purpose is to generate the SMT formula corresponding to C++, so I consider using ESBMC, I would like to ask if ESBMC provides corresponding functions to meet my needs:
```
#include <cassert>

int main() {
    int a, b;
    a = 1 + 1;
    b = 1 + 2;
    assert(a + b > 2); 

    return 0;
}
```

**Comment by fbrausse** [comment]
Hi @MJJ-Shuai. ESBMC can generate SMT formulas instead of solving the safety properties it normally checks with `--smtlib --smt-formula-only --output FILE.smt2`. There are other ways to generate such formulas, too, specific to each built-in solver. For that, replace `--smtlib` by, e.g., `--z3` and you will notice that the result will be a different, but equi-satisfiable, formula understandable by Z3.

This program however is a bit too simple for ESBMC to regularly invoke an SMT solver for. ESBMC will solve it directly. However, by adding the options `--unwind 1 --no-simplify` it will generate such a formula. This one for --smtlib: [gh-1829.txt](https://github.com/esbmc/esbmc/files/15291463/gh-1829.txt) Note that the `--unwind` bound is specific to this program. In general, when a program contains potentially unbounded loops, this bound could be higher or not exist at all without specialized solving strategies, such as k-induction.

You might find that the formula is relatively large compared to the given program. That is because a lot of it relates to setting up symbols required for dealing with lifetime properties of dynamically allocated objects and the address space in general.

**Comment by Sakura-0407** [comment]
@fbrausse Thanks for your quick reply, I will consider your suggestions. Besides, if I need to use cvc5,esbmc can also generate smt formula for it, right？

**Comment by fbrausse** [comment]
> @fbrausse Thanks for your quick reply, I will consider your suggestions. Besides, if I need to use cvc5,esbmc can also generate smt formula for it, right？

ESBMC at the moment doesn't have a cvc5 backend, but it does have a cvc4 one. Unfortunately, the cvc4 backend can't produce SMT output files right now (it talks to the cvc4 API directly). However, the `--smtlib` output is the most general and should be understood by all SMT-Lib v2 compliant solvers including cvc5.

**Comment by Sakura-0407** [comment]
@fbrausse Oh, I see. I will give it a try. Thank you again.

**Comment by lucasccordeiro** [comment]
@fbrausse: Can you please submit a PR to update our documentation https://ssvlab.github.io/esbmc/documentation.html#smt-backends with these commands?
