### ISSUE TITLE
[c++] Can't construct rvalue reference to array type

### ISSUE THREAD

**Issue by ChenfengWei0** [esbmc/esbmc#1962]
```cpp
class Base
{
public:
  int ss[1] = {1};
  int sss[1] = {1};
};

int main()
{
  Base x;
}
```

Result
```
ESBMC version 7.6.1 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing 1.cpp
Converting
Generating GOTO Program
GOTO program creation time: 0.470s
GOTO program processing time: 0.001s
Checking base case, k = 1
Starting Bounded Model Checking
ERROR: Can't construct rvalue reference to array type during dereference
(It isn't allowed by C anyway
```

**Comment by ChenfengWei0** [comment]
Related issue: #1934

**Comment by ChenfengWei0** [comment]
```
Symbol......: c:@S@Base@F@Base#
Module......: 1
Base name...: Base
Mode........: C++
Type........: constructor  (struct Base *)
Value.......:
{
code
  * type: code
  * operands:
    0: code
        * type: code
        * throw_decl_id: noexcept
  * statement: throw_decl
*this = { .ss={ 1 }, .sss=this->sss };

*this = { .ss=this->ss, .sss={ 1 } };

}
Flags.......: lvalue
Location....: file 1.cpp line 4 column 7
```

I felt like there were some reference ordering issues. What do you think, @fbrausse  @XLiZHI ?

**Comment by XLiZHI** [comment]
```
*this = { .ss={ 1 }, .sss=this->sss };

*this = { .ss=this->ss, .sss={ 1 } };  <-- dereference ss here
```
I think that's where the problem is. The front end dereferences the `ss` when it is initialized for the `sss`.

We may need to update the initialization strategy, such as putting array type initialization into only one assignment statement.

_edit:_ For example, we can separate the initialization of array member variables into a new variable `array_initializer`, and initialize them together at the end of the body function.

**Comment by fbrausse** [comment]
> I think that's where the problem is. The front end dereferences the `ss` when it is initialized for the `sss`.

I agree.

> We may need to update the initialization strategy, such as putting array type initialization into only one assignment statement.
> 
> _edit:_ For example, we can separate the initialization of array member variables into a new variable `array_initializer`, and initialize them together at the end of the body function.

We should not separate the initialization of certain members from that of others if that results in reordering: The initialization order is the order of declarations of the (non-static) members, e.g.
```c++
#include <cstdio>

struct P { P(const char *s) { printf("P: %s\n", s); } };

struct T {
	P a[1] = { { "a[0]" }, };
	P c;
	P b = "b";
	T() : c("c"), b("b2") { printf("T()\n"); }
};

int main()
{
	T t;
}
```
prints this order
```
P: a[0]
P: c
P: b2
T()
```
This order is guaranteed; from [class.base.init 13.3](http://eel.is/c++draft/class.base.init#13.3):
> Then, non-static data members are initialized in the order they were declared in the class definition (again regardless of the order of the [mem-initializer](http://eel.is/c++draft/class.base.init#nt:mem-initializer)s)[.](http://eel.is/c++draft/class.base.init#13.3.sentence-1)

**Comment by fbrausse** [comment]
Which means, the approach of incrementally building the object member by member by dereferencing the `this` pointer in https://github.com/esbmc/esbmc/pull/1938#issuecomment-2233227257 does not work. Sorry, I didn't think about this case.

Instead, we could try to go about it this way:
1. Introduce a new symbol in the constructor function, initialized by dereferencing the entire `this`.
2. Use assignments to the members of the new symbol, same as before #1938.
3. After each member assignment in item 2., assign `*this` with the updated value of the new symbol. This is necessary, because the next member (or base class) initializer might use the value of the previous members.

The downsides are:
- A new "unnecessary" symbol for each constructor, which the slicer probably can't remove, because it's being used multiple times with member-expressions. But maybe the slicer could be told about this pattern...
- Multiple `*this` dereferences for the member assignments.
- We must be careful to not take the address of the new symbol, because it should be the same as `this` but won't be.

**Comment by XLiZHI** [comment]
> We should not separate the initialization of certain members from that of others if that results in reordering: The initialization order is the order of declarations of the (non-static) members

What if we combine all the initializations?

I don't think this affects the order of initialization, because the frontend calls the constructors in order.

```
        DECL P tmp$1;

        ASSIGN tmp$1=NONDET(struct);

        DECL P tmp$2;

        ASSIGN tmp$2=NONDET(struct);

        DECL P tmp$3;

        ASSIGN tmp$3=NONDET(struct);
 
        FUNCTION_CALL:  P(&tmp$1, &"a[0]"[0])
 
        FUNCTION_CALL:  P(&tmp$2, &"c"[0])
 
        FUNCTION_CALL:  P(&tmp$3, &"b2"[0])
        
         ASSIGN *this={ .a={ tmp$1 }, .c=tmp$2, .b=tmp$3 };
```

**Comment by fbrausse** [comment]
Hm, a problem with separating the symbols corresponding to the members is that initializers can refer to other members of the object, either already initialized ones (which will be fine), or uninitialized ones (which should have nondet values - unless the object is reconstructed into an existing one), e.g.
```c++
struct A {
  int p, q, &r, *s;
  A *ptr;
  A(int x) : p(x), q(p), r(q), s(&r), ptr(this) {}
};
```
That's why I suggested step 3.

**Comment by XLiZHI** [comment]
I now think of two ways to implement it:

1. We add this symbol directly to the component of this struct. Then we might not need to declare it.
2. Just declare the new symbol in the constructor

For example, its implementation looks like this:
```cpp
class Base
{
public:
  int ss[1] = {1};
  int sss[1] = {1};
};

int main()
{
  Base x;
}
```
```
DECL Base init_symbol;

ASSIGN init_symbol.ss={1};
 
ASSIGN *this = init_symbol;
 
ASSIGN init_symbol.sss={1};
 
ASSIGN *this = init_symbol;
```

**Comment by fbrausse** [comment]
@XLiZHI Your example of the second way is what I had in mind. I don't quite understand what your first way of implementing means. Could you explain?

**Comment by XLiZHI** [comment]
> @XLiZHI Your example of the second way is what I had in mind. I don't quite understand what your first way of implementing means. Could you explain?

Here is the example:
https://github.com/esbmc/esbmc/blob/123faaa0ecda77a1ee98242ced8d20a84a2f5ab7/src/cpp/cpp_typecheck_bases.cpp#L83-L94
But I realized that we still need to dereference this component if we modify it like this.

**Comment by fbrausse** [comment]
#1943 is possibly related since it also is about a struct with multiple arrays as members.
