### ISSUE TITLE
separate compilation? main symbol `main' not found

### ISSUE THREAD

**Issue by dckc** [esbmc/esbmc#355]
I tried to check [xsJSON.c](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/sources/xsJSON.c) but got:

```
main symbol `main' not found
CONVERSION ERROR
```

Why is lack of `main` an error? Is separate compilation not (yet?) supported? Is it considered in-scope for the project? Perhaps I missed some documentation on how to do it?

**Comment by lucasccordeiro** [comment]
Since you don't have a `main` function as an entry point, you need to specify which function you want to verify. In this specific case, you could:

$esbmc xsJSON.c --function  fx_JSON_parse 

If you want to automate the process of verifying each function individually, we also have a python script to do that job for you. 

Do you have some test suite to check this piece of code? you could also extend this test suite to automated the verification process. You could take a look at this paper https://ssvlab.github.io/lucasccordeiro/papers/ecbs2010.pdf (cf. Section 2.2).

Please let us know if you need further support to use ESBMC in your project.

Best,
Lucas

**Comment by dckc** [comment]
Now I get a SEGV. I can't figure out how to get a core file to give you a back trace even with `ulimit -c unlimited`. I suppose that's a separate issue... (_p.s. #359_) how to do separate compilation is now clear enough.

```
ESBMC version 6.6.0 64-bit x86_64 linux
file /home/connolly/projects/moddable/xs/sources/xsJSON.c: Parsing
Converting
Generating GOTO Program
xsnap.mk:120: recipe for target 'tmp/lin/release/xsnap/xsJSON.o' failed
make: *** [tmp/lin/release/xsnap/xsJSON.o] Segmentation fault
```

**Comment by lucasccordeiro** [comment]
If you could open another issue, then we could take a look at it and propose a fix.
