### ISSUE TITLE
std:bad_cast on csmith

### ISSUE THREAD

**Issue by pmatos** [esbmc/esbmc#4]
Hi,

Got a `std:bad_cast` on esbmc running on generated test for compilers.
Attached file. Ran command line:
```
$ installs/esbmc-v4.6.0-linux-static-64/bin/esbmc --k-induction prog.i
```
[prog.i.gz](https://github.com/esbmc/esbmc/files/1595211/prog.i.gz)

**Comment by pmatos** [comment]
Happy new year!

**Comment by pmatos** [comment]
Here's a simpler one to look at:

```
$ cat prog.i
union {
  short a
} b, *c = &b;
main() { *c; }
```

**Comment by jmorse** [comment]
Hi Paulo,

Thanks for the fault report -- compiled without NDEBUG, a `is_struct_type(type)` assertion triggers in ` dereferencet::construct_struct_ref_from_const_offset_array`. It looks like this is due to incomplete union work. We recently changed the underlying storage of all unions to be byte arrays, and figured
 * All union field accesses become dereferences of non-union type, which we can handle
 * C99 assignments of unions become memcpy's from the clang frontend (I think)

Which avoids us having to ever construct a union during a dereference.

IIRC the C spec for your example requires `*c` to be "evaluated", but instead ESBMC goes too far by attempting to create a union out of the underlying byte array and croaks. The solution is probably to encode some pointer validity and bounds checks, and skip any reference building. Fitting that into existing abstractions is tricky, it'll probably be a few days until there's a patch.

(Happy new year!).
