### ISSUE TITLE
Support custom sized bitvectors

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#51]
Request from the cseq team.

They're using frama-c to do some interval analysis and define custom bitvectors with arbitrary size. In a number of cases, the verification time is much smaller.

CBMC uses this weird semantic:
__CPROVER_bitvector[10] a;

Obviously, the clang frontend will not allow that, even if we define the __CPROVER_bitvector type.

The easiest solution I could come up is to use source annotations, which we already use for infinite sized arrays. I propose something like:

__attribute__((annotate("bv=10"))) 
int a;

This is parsed by clang, we can still compile the code and it will require little effort to implement.

The down side: it will only be supported by the new frontend.

**Comment by lucasccordeiro** [comment]
This issue is obsolete. We already handle custom size bitvectors:


https://github.com/esbmc/esbmc/tree/master/regression/esbmc/bitvector_01
https://github.com/esbmc/esbmc/tree/master/regression/esbmc/bitvector_02
https://github.com/esbmc/esbmc/tree/master/regression/esbmc/bitvector_03
https://github.com/esbmc/esbmc/tree/master/regression/esbmc/bitvector_04
