### ISSUE TITLE
[SMT backend] check Boolector version used in SV-COMP 2021

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#903]
```
**But please note that there is a large regression in ESBMC:
We compared ESBMC from SV-COMP 2022 and 2021, and the earlier was much better, therefore, we used the earlier version for the paper.
Also, for the camera-ready paper, we tried the 2023 version and wanted to use the latest version, but also this was not as good as the 2021 version.
Do you know why?

Here the latest results from SV-COMP:
https://sv-comp.sosy-lab.org/2023/results/results-verified/unreach-call.ReachSafety-Hardware.table.html#/quantile?selection=cpu&plot=Quantile%20Plot

https://sv-comp.sosy-lab.org/2023/results/results-verified/unreach-call.ReachSafety-Hardware.table.html#/table**

```

**Comment by lucasccordeiro** [comment]
@mikhailramalho, @fbrausse, @rafaelsamenezes: do you have any thoughts here?

**Comment by mikhailramalho** [comment]
Large regression in which category?

**Comment by lucasccordeiro** [comment]
Hardware category.

**Comment by lucasccordeiro** [comment]
@shmarovfedor : could you please check whether your implementation of the bitfield support has influenced the ESBMC performance for these benchmarks?

As far as I remember, we had no support for bitfields in 2021.

**Comment by shmarovfedor** [comment]
I've just done a quick analysis of the Hardware category. None of the files (2448) have any structs or unions. Also they do not seem to have any pointers. So in my opinion, the bit fields patch is out of question (since the implementation only modifies the `dereference` module). 

In general, it looks like that this category is quite hard to verify. Almost all of the programs have over 1k lines of code (with some of them with over 100k lines of code!!). CPAChecker - the top scorer in the Hardware category in SV-COMP 2023 - scored 281 points out of 1950, and ESBMC (the 2023 version) came second with 214. At the same time, it is hard to judge the scale of the ESBMC performance difference from the message above. Also over the past two years we applied many patches to ESBMC, and it is very hard (if not impossible) to pinpoint the exact reason.
