### ISSUE TITLE
[Operational Model] check the scanf implementation 

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#955]
ESBMC gives VERIFICATION SUCCESSFUL for this program:

```C
#include <stdio.h>
int main( int argc, char *argv[])
{       
        char reg_name[12];
        printf("Enter your username:");
        scanf("%s", reg_name); //Buffer overflow here
        printf("The program is now registered to %s.\n",reg_name);
        return 0;
}
```

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes : Can I ask you to check this issue since you're the author of the scanf OM?

**Comment by lucasccordeiro** [comment]
This issue is related to this PR https://github.com/esbmc/esbmc/pull/872.

**Comment by ChenfengWei0** [comment]
Ok, I will work on it.

**Comment by ChenfengWei0** [comment]
The CBMC generates same result as ESBMC.
```sh
$ cbmc test.cpp
CBMC version 5.80.0 (cbmc-5.80.0) 64-bit x86_64 linux
Parsing 4.cpp
Converting
Type-checking 4
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
**** WARNING: no body for function scanf
Runtime Symex: 0.00139503s
size of program expression: 68 steps
simple slicing removed 0 assignments
Generated 0 VCC(s), 0 remaining after simplification
Runtime Postprocess Equation: 3.7952e-05s
VERIFICATION SUCCESSFUL
```

**Comment by lucasccordeiro** [comment]
Thanks, @ChenfengWei0.

We should provide `VERIFICATION FAILED`. There is a buffer overflow here.

**Comment by lucasccordeiro** [comment]
Note that CBMC reports:

```
**** WARNING: no body for function scanf
```

**Comment by lucasccordeiro** [comment]
@ChenfengWei0 : you can also take a look at this issue https://github.com/esbmc/esbmc/issues/508.

**Comment by ChenfengWei0** [comment]
A short update of my progress and thoughts:

- I think we should add a `goto_trace_stept::typet INPUT`  for `scanf/fscanf`, i.e.
```c++
  typedef enum
  {
    ASSIGNMENT,
    ASSUME,
    ASSERT,
    OUTPUT,
    INPUT,  // added. CBMC also has this type
    SKIP,
    RENUMBER
  } typet;
```
So that we can have function `input()` to print out the debug info. e.g. 
```c++
// we already had output
void symex_target_equationt::output(
  const expr2tc &guard,
  const sourcet &source,
  const std::string &fmt,
  const std::list<expr2tc> &args)
{
  SSA_steps.emplace_back();
  SSA_stept &SSA_step = SSA_steps.back();

  SSA_step.guard = guard;
  SSA_step.type = goto_trace_stept::OUTPUT;
  SSA_step.source = source;
  SSA_step.output_args = args;
  SSA_step.format_string = fmt;

  if(debug_print)
    debug_print_step(SSA_step);
}

// added
void symex_target_equationt::input(...)
{
...
SSA_step.type = goto_trace_stept::INPUT;
...
if(debug_print)
    debug_print_step(SSA_step);
}
```
and we can call this function at the end of `goto_symext::symex_fscanf/symex_scanf` by `target->intput(cur_state->guard.as_expr(), cur_state->source, fmt.as_string(), args);`

- About the verification of `scanf`. #872 have done the **underflow** checks for `fscanf`, which can be easily adapted to `scanf`. For **overflow**, we can limit the input string by calling for example:
```c++
char buf[21];
scanf("%20s", buf);  // last destination buffer element is for null byte
```
- So my idea is to add an assertion comparing the **format string** (`op[0]` for `scanf` / `op[1]` for `fscanf`) and array size. e.g. 
1. obtain the `input_limit`. If no limit info in format string, then `input_limit = inf`. For the example above, is `"%20s"`.
2. obtain the corresponding `var`  from `va_list` 
3. add an assertion:
```c++
assert(input_limit+1 <= var.size(), "buffer overflow here");
```
- If the assertion approach make sense, then we should also consider constructing other variable types i.e int/float/char/pointer...

**Comment by mikhailramalho** [comment]
Can't we add the asserts at goto-check?

**Comment by ChenfengWei0** [comment]
> Can't we add the asserts at goto-check?

Thanks for the suggestions. 

My intuition is that we can add the asserts at goto-check, by either extending the function `goto_check::overflow_check()` or adding a specific function like `input_overflow_check()`. For now, I need to look further into the goto-check code.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/issues/984.
