### ISSUE TITLE
ToUnion does not support bitfields

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#994]
The following code:

```c
#include <stdbool.h>

#include <stdint.h>



typedef struct {

                unsigned long int tmp1: 64;

} struct_1;



typedef union {

    unsigned int raw : 2;

    struct {

        unsigned int x1 : 1;

        unsigned int x2 : 1;

    };

} union_1;



void func(struct_1 *tmp_p);



void func(struct_1 *tmp_p) {

    union_1 tmp1 = (union_1)(uint32_t)(tmp_p->tmp1);

}
```

Fails with `ERROR: Couldn't map type  into the union`

This is mainly due to how ESBMC handles struct equivalence at https://github.com/esbmc/esbmc/blob/master/src/clang-c-frontend/typecast.cpp#L43

**Comment by fbrausse** [comment]
GCC in versions 9.4.0, 10, 11 and 12 rejects this code with
```
gh-994.c: In function 'func':
gh-994.c:24:18: error: cast to union type from type not present in union
   24 |   union_1 tmp1 = (union_1)(uint32_t)(tmp_p->tmp1);
      |                  ^
```
Curiously, Clang (with `-Wpedantic`) in contrast claims
```
gh-994.c:24:18: warning: cast to union type is a GNU extension [-Wgnu-union-cast]
  union_1 tmp1 = (union_1)(uint32_t)(tmp_p->tmp1);
                 ^        ~~~~~~~~~~~~~~~~~~~~~~~
```
It might not be worth supporting this non-standard [cast-to-union](https://gcc.gnu.org/onlinedocs/gcc/Cast-to-Union.html)-like feature.

**Comment by fbrausse** [comment]
Though the modification
```
    unsigned int raw : 32;
```
is accepted by GCC (and Clang) and still fails to pass gen_typecheck. However, an unnamed bitfield component of the right size in the union,
```
union U { unsigned : 32; };
```
is *rejected* by Clang but accepted by GCC. @rafaelsamenezes What are the expected semantics here?

**Comment by lbenpora** [comment]
As requested by @rafaelsamenezes, here is the context to the firmware that we are verifying:
- LLVM clang version 11.0
- Flags: clang -Oz -ffreestanding -fno-unroll-loops -fno-jump-tables

The FW code we are working on is characterized by:
-	Integer operation only. No floating point operations.
-	Mostly unsigned variables. Very rare to see signed variables.
-	Heavy work with structs that use the bit sign “:” e.g., 
struct str {
  union {
   raw : 32
  {
   unsigned x : 16;
   unsigned y : 16;
  }
}
-	Each struct is usually mapped to a HW 32bit or 64bit register
-	Code is also characterized with heavy bit manipulations with the above structs.
-	Finally, heavy usage of extern variables defined outside the scope of the FW.

Hope this helps.

**Comment by fbrausse** [comment]
@lbenpora Many thanks for these clarifications. I'm looking into a possible fix that preserves Clang's semantics. I should note though that this usage of [cast-to-union](https://gcc.gnu.org/onlinedocs/gcc/Cast-to-Union.html) is not portable (not even between GCC and Clang, see above comments). However, if you're not mixing C with C++, a portable alternative would be being explicit about which component is initialized using [compound literals](https://en.cppreference.com/w/c/language/compound_literal):
```c
(struct str){ .raw = value_32bit }
```
or
```c
(struct str){ .x = value_16bit }
```
This construction is supported by ESBMC though it might be worth noting that it is not entirely equivalent since the cast-to-union expressions are not lvalues - unlike compound literals.
